# config/app.yml for rails-settings-cached
defaults: &defaults
  club: "OpenService"
  navbarColor: "#e3f2fd"
  navbarStyle: "light"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
